Misc Quality of Life and Bug fixes
TorqueGameEngines/Torque3D pull request #550
Opened 2021-08-28 23:52 UTC by Areloch

Added handling for if preview images on image assets fails to generate, will fallback to using the full image
Added handling for double clicking or drag-n-dropping terrain assets to create them
Improved handling of field labels in variable inspector by making the stringtable be case sensitive.
Added editor settings for handling of asset double click behavior. Can now select between Edit Asset and Spawn Asset. Support is asset type dependent.
Added editor setting for auto-importing loose files when navigating to a folder. If on and the user has flagged to also enable auto-import generally, will auto import all unaffiliated loose files in as assets.
Added editor setting for default module to use when creating new assets. Updated various tooling logic so when creating a new material, if this and the 'Always Prompt Module Target' setting is off, it will fill in the target module and target asset path info based on the default module.
Fixed issue with editors that use managedData scripts where if the path didn't exist, the script file wouldn't be made.
Fixed display issue in terrain editor where if you clear the detail map, the normal/macro/orm maps would disable, but not also clear.
Fixed handling of cleared maps in terrain editor so it no longer fills empty maps in with the no image image.
Fixed handling of creating new material where it would fill in the diffuse with a no texture image as the default.
Fixed issue where canceling out of creating a module would still prompt to create the common default folders.
Fixed issue where the Select Module window couldn't be closed via the cancel or x buttons.
Based on feedback, reduced default size of the Text Pad window.
Fixed issue where the Drop At menu list wouldn't correctly display which item was marked after it was changed.
Fixed spawning shape asset handling so it uses whatever the editor's Drop At setting is.
Improved themeing of regular bitmap buttons in the editor.
Based on feedback, flipped layout of Target Module and Target Path in the Create New Asset window.
Improved handling of setting up the Target Path for when creating new assets. If a path is not set, and the user has a Default Module, it will default the path to that module.

2021-08-29 01:24 UTC, JeffProgrammer requested changes

2021-08-29 01:24 UTC, JeffProgrammer commented on Templates/BaseGame/game/tools/worldEditor/scripts/menuHandlers.ed.tscript
> +   for(%i=0; %i < %this.getItemCount() + 1; %i++)
item count + 1? Does this go over the array?

2021-08-29 22:39 UTC, JeffProgrammer approved these changes

2021-08-30 00:49 UTC, lukaspj commented on Templates/BaseGame/game/tools/assetBrowser/scripts/addModuleWindow.tscript
> +   //eval(AssetBrowser_addModuleWindow.callbackFunction);
Might as well just delete the line

2021-08-30 00:49 UTC, lukaspj commented on Templates/BaseGame/game/tools/assetBrowser/scripts/assetTypes/image.tscript
> +      {
Indentation below this line looks off

2021-08-30 00:49 UTC, lukaspj commented on Templates/BaseGame/game/tools/assetBrowser/scripts/assetTypes/shape.tscript
> +         %previewData.doubleClickCommand = "AssetBrowser.onShapeAssetEditorDropped( "@%assetDef@" );";
Generally I think if you don't have braces it should be a single line. I'd prefer braces here

2021-08-30 00:49 UTC, lukaspj commented on Templates/BaseGame/game/tools/assetBrowser/scripts/assetTypes/shape.tscript
> +   }*/
Might as well delete the code

2021-08-30 00:49 UTC, lukaspj commented on Templates/BaseGame/game/tools/gui/profiles.ed.tscript
> +	//bitmapAsset = "ToolsModule:button_image";
Delete This line instead

2021-09-01 23:04 UTC, merged